# 05 Evaluación de Modelos

## 1. Cargar Datos Procesados

In [11]:
## 1. Cargar el Conjunto de Datos
# Importar la librería necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Seleccionar el tipo de balanceo a utilizar
tipo_balanceo = 'oversampled' # 'original', 'oversampled', 'undersampled'

if tipo_balanceo == 'original':
    dir_path = '../data/interim'
elif tipo_balanceo == 'oversampled':
    dir_path = '../data/processed/oversampled'
elif tipo_balanceo == 'undersampled':
    dir_path = '../data/processed/undersampled'

# Cargar el conjunto de datos
X_test = pd.read_csv(f'{dir_path}/X_test.csv')
y_test = pd.read_csv(f'{dir_path}/y_test.csv')

# Mostrar los primeros registros de los datos de entrenamiento
X_test.head()

age  default   balance  housing  loan       day  duration  campaign  \
0  0.285714        0  0.089318        0     0  0.133333  0.080927  0.016129   
1  0.519481        0  0.079041        1     0  0.966667  0.069337  0.016129   
2  0.285714        0  0.072840        0     0  0.966667  0.012810  0.032258   
3  0.311688        0  0.075654        1     1  0.533333  0.147824  0.016129   
4  0.803158        0  0.075402        0     0  0.861847  0.033223  0.000000   

      pdays  previous  ...  month_jul  month_jun  month_mar  month_may  \
0  0.000000  0.000000  ...      False       True      False      False   
1  0.000000  0.000000  ...      False      False      False      False   
2  0.000000  0.000000  ...       True      False      False      False   
3  0.000000  0.000000  ...      False      False      False      False   
4  0.030015  0.002629  ...      False      False      False      False   

   month_nov  month_oct  month_sep  poutcome_other  poutcome_success  \
0      False      False      False           False             False   
1      False      False      False           False             False   
2      False      False      False           False             False   
3      False      False      False           False             False   
4      False       True      False           False             False   

   poutcome_unknown  
0              True  
1              True  
2              True  
3              True  
4              True  

[5 rows x 42 columns]

## 2. Cargar Modelos Preentrenados

In [12]:
import joblib

# Carga Modelos preentrenados
lr = joblib.load('../models/1_lr_model.pkl')
dt = joblib.load('../models/2_dt_model.pkl')
rf = joblib.load('../models/3_rf_model.pkl')
gb = joblib.load('../models/4_gb_model.pkl')
knn = joblib.load('../models/5_knn_model.pkl')
nb = joblib.load('../models/6_nb_model.pkl')
mlp = joblib.load('../models/7_mlp_model.pkl')
# svc = joblib.load('../models/8_svc_model.pkl')

## 3. Evaluacion de Modelos

### 3.1. Entrenamiento de un Modelo de Regresión Logística

In [13]:
# Hacer predicciones en el conjunto de prueba
y_pred_lr = lr.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print("Classification Report:\n", classification_report(y_test, y_pred_lr))

Accuracy: 0.8509593707730073
Confusion Matrix:
 [[8538 1447]
 [1528 8448]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.86      0.85      9985
           1       0.85      0.85      0.85      9976

    accuracy                           0.85     19961
   macro avg       0.85      0.85      0.85     19961
weighted avg       0.85      0.85      0.85     19961



### 3.2. Entrenamiento de un Modelo de Árbol de Decisión

In [14]:
# Hacer predicciones en el conjunto de prueba
y_pred_dt = dt.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("Classification Report:\n", classification_report(y_test, y_pred_dt))

Accuracy: 0.8914884023846501
Confusion Matrix:
 [[8837 1148]
 [1018 8958]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.89      0.89      9985
           1       0.89      0.90      0.89      9976

    accuracy                           0.89     19961
   macro avg       0.89      0.89      0.89     19961
weighted avg       0.89      0.89      0.89     19961



### 3.3. Entrenamiento de un Modelo de Bosque Aleatorio

In [15]:
# Hacer predicciones en el conjunto de prueba
y_pred_rf = rf.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

Accuracy: 0.9384800360703371
Confusion Matrix:
 [[9067  918]
 [ 310 9666]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.91      0.94      9985
           1       0.91      0.97      0.94      9976

    accuracy                           0.94     19961
   macro avg       0.94      0.94      0.94     19961
weighted avg       0.94      0.94      0.94     19961



### 3.4. Entrenamiento de un Modelo de Gradiente Boosting

In [16]:
# Hacer predicciones en el conjunto de prueba
y_pred_gb = gb.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))
print("Classification Report:\n", classification_report(y_test, y_pred_gb))

Accuracy: 0.9042633134612494
Confusion Matrix:
 [[8866 1119]
 [ 792 9184]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.89      0.90      9985
           1       0.89      0.92      0.91      9976

    accuracy                           0.90     19961
   macro avg       0.90      0.90      0.90     19961
weighted avg       0.90      0.90      0.90     19961



### 3.5. Entrenamiento de un Modelo de K-Nearest Neighbors

In [17]:
# Hacer predicciones en el conjunto de prueba
y_pred_knn = knn.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))

Accuracy: 0.8856269725965633
Confusion Matrix:
 [[8302 1683]
 [ 600 9376]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.83      0.88      9985
           1       0.85      0.94      0.89      9976

    accuracy                           0.89     19961
   macro avg       0.89      0.89      0.89     19961
weighted avg       0.89      0.89      0.89     19961



### 3.6. Entrenamiento de un Modelo de Naive Bayes

In [18]:
# Hacer predicciones en el conjunto de prueba
y_pred_nb = nb.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))
print("Classification Report:\n", classification_report(y_test, y_pred_nb))

Accuracy: 0.7104353489304143
Confusion Matrix:
 [[8589 1396]
 [4384 5592]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.86      0.75      9985
           1       0.80      0.56      0.66      9976

    accuracy                           0.71     19961
   macro avg       0.73      0.71      0.70     19961
weighted avg       0.73      0.71      0.70     19961



### 3.7. Entrenamiento de un Modelo de Red Neuronal

In [19]:
# Hacer predicciones en el conjunto de prueba
y_pred_mlp = mlp.predict(X_test)

# Evaluar el modelo
print("Accuracy:", accuracy_score(y_test, y_pred_mlp))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_mlp))
print("Classification Report:\n", classification_report(y_test, y_pred_mlp))

Accuracy: 0.9019588196984119
Confusion Matrix:
 [[8775 1210]
 [ 747 9229]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.88      0.90      9985
           1       0.88      0.93      0.90      9976

    accuracy                           0.90     19961
   macro avg       0.90      0.90      0.90     19961
weighted avg       0.90      0.90      0.90     19961



### 3.8. Entrenamiento de un Modelo de Support Vector Machine (demora mucho)

In [20]:
# Hacer predicciones en el conjunto de prueba
# y_pred_svc = svc.predict(X_test)

# Evaluar el modelo
# print("Accuracy:", accuracy_score(y_test, y_pred_svc))
# print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svc))
# print("Classification Report:\n", classification_report(y_test, y_pred_svc))